### ISSUE TITLE
Nested diffs / Struct diffs

### ISSUE THREAD

**Issue by breml** [PieterD/diff#1]
We build a small tool which uses a modified version of your library. For our use case (context aware diff of hierarchical configuration files) we needed some kind of nested diffs of nested structs.

Therefore we extended your library to support this use case. You find the relevant diff in our github repository: https://github.com/u-s-p/diff/commit/72d95a8ab24e6166508fd5a526a310159da889d3

The relevant changes are in delta.go, interface.go and lcs.go (all other file contain tests and/or changed import paths).

If you are interested in a pull request, let me know, otherwise just close this issue.

**Comment by PieterD** [comment]
Thanks for the heads-up!

Unfortunately, the changes you've made are api-breaking, and a few of us use this library in quite a lot of code, so I can't pull in your changes without breaking a lot of builds :)

The changes also look quite specific to your use-case. I toyed with the idea of making it an n-level diff, but scratched the idea when I realized we could, in the one place we needed it, just call diff recursively.

But I'm glad this was useful to you, and hope I've saved you at least a little bit of work :)

**Comment by breml** [comment]
@PieterD Thanks for your rapid answer. You are perfectly right, the breaking of the API is a no go. This got me thinking and I decided to refactor my change to an API compatible version. Just for your info:
https://github.com/u-s-p/diff/commit/9c19959f561a1688644156919ae3a6f8d6cfeab6
